# yaranullin/events.py
#
# Copyright (c) 2012 Marco Scopesi <marco.scopesi@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

''' The events of Yaranullin ''' 

# Basic
ANY = 0
QUIT = 1
TICK = 2
CACHE_GET = 3
CACHE_SEND = 4

# Network
JOIN = 10
RESOURCE_REQUEST = 11
RESOURCE_UPDATE = 12

# Game
GAME_REQUEST_PAWN_NEW = 20
GAME_REQUEST_PAWN_DEL = 21
GAME_REQUEST_PAWN_UPDATED = 22
GAME_REQUEST_PAWN_MOVE = 23
GAME_REQUEST_PAWN_PLACE = 24
GAME_REQUEST_PAWN_NEXT = 25
GAME_REQUEST_BOARD_NEW = 26
GAME_REQUEST_BOARD_DEL = 27
GAME_REQUEST_BOARD_CHANGE = 28
GAME_REQUEST_UPDATE = 29
GAME_EVENT_UPDATE = 30
GAME_EVENT_PAWN_NEXT = 31
GAME_EVENT_PAWN_UPDATED = 32
GAME_EVENT_BOARD_CHANGE = 33
